### ISSUE TITLE
Inspect all crates and cover them by tests

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#1496]
@gear-tech/dev

We need to inspect each of our crates carefully and completely cover them by unit (and integration if necessary) tests. This is the tracking issue to check the overall progress. Please choose the crate that was maintained by another developer and mark it with your nickname. Feel free to create a particular issue if needed.

As a result, new issues with found problems and PRs with new tests and fixes are to be created.

First order:

- [x] `gear-backend-common` @SabaunT #1711
- [ ] `gear-backend-sandbox`
- [ ] `gear-backend-wasmi`
- [ ] `gear-cli`
- [ ] `gear-common`
- [ ] `gear-common-codegen`
- [x] `gear-core` @ark0f #1747
- ~~`gear-core-errors`~~ (only enums)
- [x] `gear-core-processor` @shamilsan #1693
- [ ] `gear-lazy-pages`
- [ ] `gear-runtime`
- [ ] `gear-runtime-common`
- [ ] `gear-runtime-interface`
- [ ] `gear-runtime-primitives`
- [ ] `gear-runtime-test-cli`
- [ ] `gear-service`
- ~~`gear-test`~~ Not used in production, only for debug
- ~~`pallet-airdrop`~~ Scheduled to be removed before release
- [ ] `pallet-gear`
- [ ] `pallet-gear-debug`
- [ ] `pallet-gear-gas`
- [ ] `pallet-gear-messenger`
- [ ] `pallet-gear-payment`
- [ ] `pallet-gear-proc-macro`
- [ ] `pallet-gear-program`
- [ ] `pallet-gear-rpc`
- [ ] `pallet-gear-rpc-runtime-api`
- [ ] `pallet-gear-scheduler`
- [ ] `vara-runtime`

Second order:

- ~~`galloc`~~ Simple wrapper around `dlmalloc`
- [ ] `gclient`
- [ ] `gcore`
- [ ] `gstd`
- [ ] `gtest`

Third order:

- [ ] `wasm-builder`
- [ ] `node-loader`

**Comment by breathx** [comment]
Related to `core-backend-sandbox` and `core-backend-wasmi`: need to introduce some demo written with `gcore` or `gstd`, that contains usage of all syscalls (without any business-logic) dependent on payload (some enum with call arguments).
Need to provide test for this demo, calling all of the existing variants in `pallet-gear` unit tests and within the `gclient` lib on the real running node: this will force us to check the behaviour of both backends and `gcore` implementations.

If I'm not mistaken, @SabaunT wants to pick this task

**Comment by SabaunT** [comment]
> Related to `core-backend-sandbox` and `core-backend-wasmi`: need to introduce some demo written with `gcore` or `gstd`, that contains usage of all syscalls (without any business-logic) dependent on payload (some enum with call arguments). Need to provide test for this demo, calling all of the existing variants in `pallet-gear` unit tests and within the `gclient` lib on the real running node: this will force us to check the behaviour of both backends and `gcore` implementations.
> 
> If I'm not mistaken, @SabaunT wants to pick this task

right

**Comment by SabaunT** [comment]
Gas tree properties **must** be reviewed and covered by property tests after [https://github.com/gear-tech/gear/pull/1730](https://github.com/gear-tech/gear/commit/8033bf0e06de5d2d3fce2f4fdb98bae07e981725). @ark0f Please introduce property tests on nodes, which are not "separated" from the tree structure.

**Comment by breathx** [comment]
Most of required crates got covered
