### ISSUE TITLE
Vara launch checklist

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#1573]
It's a tracking issue to check the overall progress in completing preparations for the launch of the Vara network.

# Contracts API

- [x] #1528
- [x] #1208
- [x] #1293

# Testing & Stability

- [x] #1568
- [x] #1602
- [x] #1601
- [x] #1451
- [x] #1382
- [x] #1531
- [x] #1496 
- [x] #1390
- [x] #1728
- [x] #1729
- [ ] #1364
- [ ] #1648
- [x] #1731
- [x]  #1723
- [x] #1724

# Economics & Consensus Related

- [x] #1511 
- [x] #1514
- [x] #1569
- [x] #1570
- [x] #1239
- [x] #1277
- [x] #1571
- [x] #1572

# Tech Documentation

- [x] https://github.com/gear-tech/wiki/issues/282
- [x] https://github.com/gear-tech/wiki/issues/283
- [x] https://github.com/gear-tech/wiki/issues/284
- [x] https://github.com/gear-tech/wiki/issues/285

**Comment by breathx** [comment]
Tracking issue no more required
