### ISSUE TITLE
Improve new meta approach

### ISSUE THREAD

**Issue by shamilsan** [gear-tech/gear#2119]
There are some issues with the new meta that are to be fixed:

- [x] No doc comments are allowed inside the trait under `#[metawasm]` attribute-like macro:

    ```rust
    #[metadata]
    pub trait Metawasm {
        /// Doc-comment
        fn method(state: Self::State) -> ... { ... }
    }
    ```

    `error: Functions should not contain attributes`

- [x] No tuple arguments are allowed in methods inside the trait under `#[metawasm]` attribute-like macro:

    ```rust
    #[metadata]
    pub trait Metawasm {
        fn method(arg: (Type1, Type2)) -> ... { ... }
    }
    ```

    `error: Illegal type specification: should be path-based`

    Workaround: use type alias
    
- [ ] Better would be to generate `.metahash` and `meta.txt` in the `target` directory to not add them to `.gitignore`
- [ ] Better to name `meta.txt` according to the Wasm binary file to have several of them in the workspace's `target` directory (say `my_app.meta.txt`)

**Comment by breathx** [comment]
meta.txt should be kept in repo with contract, partially agree with .metahash, but it will cause bad syntax within the contract. But we can insert metahash import with data section in gear wasm builder
