### ISSUE TITLE
Upgrade RPC-tests

### ISSUE THREAD

**Issue by NikVolf** [gear-tech/gear#71]
RPC tests are disabled at the moment.

- [x] should verify log and program memory: #135
- [x] should never hang: #73
- [x] should suppress node log and show it in case of error: #74 
- [ ] should show pretty diagnostic
- [ ] #353
